import './style.css';
const API='';
const app=document.querySelector('#app');
app.innerHTML=`<header><b>PLAY//OFF</b><span>OVERLAY STUDIO · SERVER RENDER</span></header><main><section class="panel"><h2>1. Vidéo</h2><label class="upload">IMPORTER MP4 / MOV<input id="pick" type="file" accept="video/*"></label><p id="file">Aucune vidéo</p><h2>2. Hook</h2><textarea id="hook" placeholder="Ton hook…\nDeuxième ligne violette"></textarea><label>Durée <b id="dv">3.0 s</b></label><input id="duration" type="range" min="0.5" max="15" step="0.1" value="3"><label>Taille <b id="sv">68 px</b></label><input id="size" type="range" min="36" max="110" value="68"><label>Position verticale <b id="yv">230</b></label><input id="y" type="range" min="100" max="1450" value="230"><label>Marge cadre TikTok <b id="fv">6%</b></label><input id="frameInset" type="range" min="0" max="12" step="1" value="6"><div class="note">Le cadre PLAY//OFF tourne en boucle pendant toute la vidéo. Le rendu est fait par FFmpeg natif sur le serveur, pas dans Chrome.</div><button class="go" id="go">EXPORTER LE MP4</button><div class="progress"><i id="bar"></i></div><p id="status">Prêt.</p></section><section class="preview"><div class="phone"><video id="vid" controls playsinline></video><video id="frame" src="/assets/cadre_preview.webm" autoplay muted loop playsinline></video><div id="hookPrev"></div></div></section></main>`;
const $=id=>document.getElementById(id),vid=$('vid'),hp=$('hookPrev');let input=null;
$('pick').onchange=e=>{input=e.target.files?.[0]||null;if(!input)return;$('file').textContent=input.name;vid.src=URL.createObjectURL(input);sync()};
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function wrapHook(text,size){
  const raw=String(text||'').trim(); if(!raw)return [];
  const explicit=raw.split(/\n/).map(x=>x.trim()).filter(Boolean);
  if(explicit.length>1)return explicit.slice(0,2);
  const words=raw.split(/\s+/); if(words.length<2)return [raw];
  const c=document.createElement('canvas'),x=c.getContext('2d'); x.font=`900 ${size}px "Archivo Black", Impact, sans-serif`;
  const max=900; let best=[raw],bestDiff=Infinity;
  for(let i=1;i<words.length;i++){const a=words.slice(0,i).join(' '),b=words.slice(i).join(' ');const wa=x.measureText(a).width,wb=x.measureText(b).width;if(wa<=max&&wb<=max){const diff=Math.abs(wa-wb);if(diff<bestDiff){best=[a,b];bestDiff=diff}}}
  return best.length===2?best:[raw];
}
function sync(){const d=+$('duration').value,s=+$('size').value,y=+$('y').value,fi=+$('frameInset').value;$('dv').textContent=d.toFixed(1)+' s';$('sv').textContent=s+' px';$('yv').textContent=y;$('fv').textContent=fi+'%';const lines=wrapHook($('hook').value,s);hp.innerHTML=lines.map((l,i)=>`<span class="l${i+1}">${esc(l)}</span>`).join('');hp.style.fontSize=(s/1920*100)+'vh';hp.style.top=(y/1920*100)+'%';hp.style.display=vid.currentTime<=d?'block':'none';const fr=$('frame');fr.style.inset=fi+'%';fr.style.width=(100-fi*2)+'%';fr.style.height=(100-fi*2)+'%'}
['hook','duration','size','y','frameInset'].forEach(x=>$(x).oninput=sync);vid.ontimeupdate=sync;sync();
async function hookBlob(text,size){await document.fonts.ready;const c=document.createElement('canvas');c.width=1000;c.height=360;const x=c.getContext('2d');x.textAlign='center';x.textBaseline='middle';x.lineJoin='round';let lines=wrapHook(text,size);lines.forEach((t,i)=>{let fs=size;x.font=`900 ${fs}px "Archivo Black", Impact, sans-serif`;while(x.measureText(t).width>900&&fs>30){fs-=2;x.font=`900 ${fs}px "Archivo Black", Impact, sans-serif`}const yy=115+i*115;x.lineWidth=14;x.strokeStyle='rgba(0,0,0,.84)';x.strokeText(t,500,yy);x.fillStyle=i===1?'#a72cff':'white';x.fillText(t,500,yy)});return await new Promise(r=>c.toBlob(r,'image/png'))}
$('go').onclick=async()=>{if(!input){$('status').textContent='Importe une vidéo.';return}const go=$('go');go.disabled=true;go.textContent='RENDU EN COURS…';$('bar').style.width='8%';$('status').textContent='Envoi de la vidéo au moteur…';try{const fd=new FormData();fd.append('video',input,input.name);fd.append('hook',await hookBlob($('hook').value,+$('size').value),'hook.png');fd.append('duration',$('duration').value);fd.append('y',$('y').value);fd.append('frameInset',$('frameInset').value);const res=await fetch('/render',{method:'POST',body:fd});if(!res.ok){let msg='Erreur serveur '+res.status;try{const j=await res.json();msg=j.error||msg}catch{}throw new Error(msg)}$('bar').style.width='92%';$('status').textContent='Rendu terminé, téléchargement…';const blob=await res.blob();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='PLAYOFF_export.mp4';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),120000);$('bar').style.width='100%';$('status').textContent='Terminé ✓ MP4 téléchargé.'}catch(e){console.error(e);$('bar').style.width='0';$('status').textContent='Erreur : '+(e?.message||e)}finally{go.disabled=false;go.textContent='EXPORTER LE MP4'}};
